### ISSUE TITLE
Does this image include "git"?

### ISSUE THREAD

**Issue by jwalters-gpsw** [nadirizr/dazel#17]
I'm thinking it doesn't since I'm seeing:
`2017/04/27 14:58:27 exec: "git": executable file not found in $PATH`

**Comment by mishas** [comment]
No. The image includes the bare minimum necessary for getting Bazel to work in a container.

You are supposed to create your own Dockerfile (`FROM dazel/dazel`) and specify it in the DAZEL_DOCKERFILE parameter of the `.dazelrc`. This file should include anything you need in your build environment (like git for example).
