### ISSUE TITLE
add nvidia-docker support

### ISSUE THREAD

**Issue by rongou** [nadirizr/dazel#19]
This is a great tool! I was trying to get tensorflow to work on GPUs, and found I had to use `nvidia-docker` to get the device driver to load. Are you open to adding support for that? I'm thinking it just needs a new parameter (something like `DAZEL_DOCKER_COMMAND`) that the user can put in .dazelrc. I can send you a pull request if you are interested. Thanks!

**Comment by mishas** [comment]
We're definitely open to adding support for that.
Moving the discussion to the code review.

Thank you for the good idea!
