### ISSUE TITLE
Building a rules_docker py_image

### ISSUE THREAD

**Issue by mtsgrd** [nadirizr/dazel#34]
I'm trying build a rules_docker python image, and am seeing the following error:

```
$> dazel build reporting/ad_hoc:cronjob
dazel build reporting/ad_hoc:cronjob
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@py_deps//': pip_import failed:  (java.io.IOException: Cannot run program "python" (in directory "/Users/mtsgrd/.cache/bazel/_bazel_mtsgrd/external/py_deps"): error=2, No such file or directory)
```

I have the following BUILD file:
```
pip_deps = [
        requirement("urllib3"),
        ...
]

py_image(
    name = "cronjob",
    srcs = glob(["*.py"]),
    deps = pip_deps,
    main = "report_cli.py"
)
```

Does this seem like an issue that can be solved by including python in the Dazel container?

**Comment by mishas** [comment]
The idea of the basic `dazel/dazel` container is to be the very minimum of things necessary for dazel to run.

If you need anything else, you should create a Dockerfile of your own (with `FROM dazel/dazel`), and have whatever you want (python for example) installed inside.

Then you should have a .dazelrc file in your project directory with `DAZEL_DOCKERFILE=./path/to/your/Dockerfile.dazel`.
