### ISSUE TITLE
Add feature for copying files from host to container

### ISSUE THREAD

**Issue by anishk25** [nadirizr/dazel#41]
Hi,

I think it will be useful to have a feature in which any file from the host can be copied to the docker container. I was thinking of adding a variable called `LOCAL_FILES` in the `.dazelrc` file. These can either be files or directories. When dazel is run these files will be copied to your workspace on the host and then you have the option to use `ADD` or `COPY` in the dockerfile to then copy these files into the container. After dazel is done running these files will be removed from the workspace. I am requesting this feature because I want copy my ssh and git credentials for a private repo onto the container.

**Comment by mishas** [comment]
You can use DAZEL_VOLUMES in your `.dazelrc` for that:
```
DAZEL_VOLUMES=/where/my/repo/ssh/keys/are/:/root/.ssh
```

Would that be sufficient?

In any case, we're trying to keep dazel as "simple" as possible - it should only run bazel within docker. It makes sense to add features that change how docker is run, but this request is something completely external - copying and deleting files during run.
I don't think we're going to do that. Sorry.

**Comment by anishk25** [comment]
Thanks that should work for my use case. I overlooked the `DAZEL_VOLUMES` parameter.
